// auth.js
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_CONFIRM = 'SET_CONFIRM';
export const RESET_LOGIN = 'RESET_LOGIN';
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';
export const LOGOUT = 'LOGOUT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const ATTEMPT_REGISTER = 'ATTEMPT_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const RESET_REGISTER = 'RESET_REGISTER';

// notifications.js
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';

// courses.js
export const FETCH_COURSE = 'FETCH_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';
export const TOGGLE_ADD_COURSE_MODAL = 'TOGGLE_ADD_COURSE_MODAL';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';
export const SET_TITLE = 'SET_TITLE';
export const SET_CODE = 'SET_CODE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_POINTS = 'SET_POINTS';
export const SET_LEVEL = 'SET_LEVEL';
export const EDIT_COURSE_TITLE = 'EDIT_COURSE_TITLE';
export const EDIT_COURSE_CODE = 'EDIT_COURSE_CODE';
export const EDIT_COURSE_DESCRIPTION = 'EDIT_COURSE_DESCRIPTION';
export const EDIT_COURSE_POINTS = 'EDIT_COURSE_POINTS';
export const EDIT_COURSE_LEVEL = 'EDIT_COURSE_LEVEL';
export const TOGGLE_EDIT_COURSE_MODAL = 'TOGGLE_EDIT_COURSE_MODAL';
export const EDIT_COURSE = 'EDIT_COURSE';
export const TOGGLE_DELETE_COURSE_MODAL = 'TOGGLE_DELETE_COURSE_MODAL';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';
